import React from 'react';
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

const Layout = ({children, authenticatedState}) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header authenticatedState={authenticatedState}/>

            <main className={`mx-auto container`}>
                {children}
            </main>

            <Footer/>
        </div>
    );
};

export default Layout;
